### ISSUE TITLE
How to customize dots and arrows?

### ISSUE THREAD

**Issue by disccaa** [BKWLD/vue-ssr-carousel#107]
How to customize dots and arrows?
my question may seem like a clusterfuck, but i'm having trouble changing it. i'm using SASS and Nuxt. I would be grateful if you could help me figure it out

**Comment by weotch** [comment]
For arrows, you can see this demo:

https://github.com/BKWLD/vue-ssr-carousel/blob/main/demo/components/demos/ui/custom-arrows.vue

You used the `back-arrow` and `next-arrow` slots. 

I don't have a demo of dots, but you would do a similar thing, using the `dot` slot.
