### ISSUE TITLE
Issue when looping activated

### ISSUE THREAD

**Issue by rodrilinares** [BKWLD/vue-ssr-carousel#112]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `vue-ssr-carousel@1.9.0` for the project I'm working on.

The problem that I faced with is when you try to go back having looping property activated. The problem is that the slide goes to the last one, which is ok, but the dots shown the second index as you can see in the next video.

https://user-images.githubusercontent.com/101422684/207106565-560af164-0812-4f73-9c03-7ef76ca45803.mov

I've "fixed" this problem with the following code, but doesn't fix it at all because the slide animation move forward instead of backward. Maybe you can improve this fix and fix it at all to make this library more robust.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/vue-ssr-carousel/index.js b/node_modules/vue-ssr-carousel/index.js
index ae566a2..9e5de4f 100644
--- a/node_modules/vue-ssr-carousel/index.js
+++ b/node_modules/vue-ssr-carousel/index.js
@@ -1747,6 +1747,9 @@ Code related to dealing with advancing between pages
     },
     // Go to a specific index
     goto: function (index) {
+      if (index < 0) {
+        index = this.pages - Math.abs(index % this.pages);
+      }
       this.index = this.applyIndexBoundaries(index);
       return this.tweenToIndex(this.index);
     },
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by edos21** [comment]
awesome job here, we have the same issue and is very confusing for the users. Thanks!

LGTM!!

**Comment by DeviLaw** [comment]
I have the same problem 🤔
