### ISSUE TITLE
NPM 2.3.0 package logs to the console

### ISSUE THREAD

**Issue by ajrowland** [BKWLD/vue-ssr-carousel#124]
Not sure where to ask this, but I've installed 2.3.0 from NPM, and the following gets logged out to the console:

```
console.log('should rendre as tablist?', this.renderAsTablist);
```

https://www.npmjs.com/package/vue-ssr-carousel?activeTab=code (line 676)

I've had to revert to 2.2.0.

It's not from the source, but can this be removed, and repackaged?

Thanks for the good work.

**Comment by weotch** [comment]
Thanks for the reminder, 2.3.1 is published to npm now
