### ISSUE TITLE
Scroll issue on mobile devices after navigation

### ISSUE THREAD

**Issue by squarif** [BKWLD/vue-ssr-carousel#128]
Issue:
Scrolling gets disabled after 1-2 seconds if I perform a swipe gesture to go back to the previous page. 

The issue occurs when I perform the gesture on the edge of the mobile screen over the carousel. All other containers work fine. I have to refresh the page to get back vertical scrolling

**Comment by weotch** [comment]
Any chance you could post a video of that?

**Comment by haroon-tahir-laam** [comment]
https://github.com/BKWLD/vue-ssr-carousel/assets/138440939/70e0b8e3-d4eb-45c9-9a23-c9adced56ee4

**Comment by haroon-tahir-laam** [comment]
> > 1000028148.mp4
> 
> @weotch kindly look into it.

@mattaebersold @brokenhd

**Comment by weotch** [comment]
Thanks for that!  I've published https://github.com/BKWLD/vue-ssr-carousel/releases/tag/v2.3.3 with your PR.  Lemme know if that fixes your issue.

**Comment by haroon-tahir-laam** [comment]
> Thanks for that! I've published https://github.com/BKWLD/vue-ssr-carousel/releases/tag/v2.3.3 with your PR. Lemme know if that fixes your issue.

Thanks, issue is fixed
