### ISSUE TITLE
[bug]Carousel, Carousel Item content flickers/glitches

### ISSUE THREAD

**Issue by sokolpaja** [BKWLD/vue-ssr-carousel#129]
[screen-capture (2).webm](https://github.com/BKWLD/vue-ssr-carousel/assets/145979550/4503cb6b-4249-42e7-bd63-06f844c35c20)

I am using vue js version 2 for this carousel the options is to peek from both sides, the issue that i have is that the cards flicker/glitches it is like it reorders when you change the slide, i have attached a video 
this is the settings of the carousel

`    <ssr-carousel
      v-if="$vuetify.breakpoint.mdAndUp"
      :key="currentLang"
      v-model="computedPage"
      loop
      peek="21%"
      show-dots
      class="slider-container"
      :responsive="[
        {
          minWidth: 960,
          gutter: 72,
          slidesPerPage: 1,
          peek: '19%',
        },
        {
          minWidth: 1264,
          slidesPerPage: 1,
          gutter: 43,
          peek: '25%',
        },
        {
          minWidth: 1904,
          slidesPerPage: 2,
          gutter: 40,
          peek: '15%',
        },
        {
          minWidth: 2450,
          slidesPerPage: 3,
          gutter: 40,
          peek: '5%',
        },
      ]"
      @change="changeSlide($event)"
    >
      <div
        v-for="(card, index) in cards"
        :key="card.key"
        class="wrap"
        @click="handleClick(index)"
      >
        <carousel-item>
          <div class="card">
            <span v-html="card.svg"></span>
            <div class="text">
              <h4 class="card__title">{{ card.title }}</h4>
              <p class="solleBlack--text">{{ card.text }}</p>
            </div>
          </div>
        </carousel-item>
      </div>
    </ssr-carousel>`

version: "vue-ssr-carousel": "^2.3.2",
stack: Nuxt with vue and vuetify
` "@nuxt/http": "^0.5.12",
    "@nuxtjs/auth": "^4.9.1",
    "@nuxtjs/axios": "^5.12.2",
    "@nuxtjs/dotenv": "^1.4.0",
    "@nuxtjs/gtm": "^2.4.0",
    "@nuxtjs/proxy": "^2.0.1",
    "@nuxtjs/pwa": "^3.0.2",`

**Comment by weotch** [comment]
Can you confirm that `cards.key` is unique for the entries in your `cards` array?

**Comment by xhuljo-inovalab** [comment]
@weotch I have the same issue. And I can confirm that the keys are different.
` [
        {
          key: 'nervous-system',
          text: this.$t('nervousSystem'),
        },
        {
          key: 'gastrointestinal-system',
          text: this.$t('gastrointestinalSystem'),
        },
        {
          key: 'immune-system',
          text: this.$t('immuneSystem'),
        },
      ]`

**Comment by xhuljo-inovalab** [comment]
@weotch We found the issue and it was us adding a css class that messed up the transition. So we can close this issue.

**Comment by weotch** [comment]
Huh, surprised a CSS class could have that effect.  Do you think it's an issue that could affect others?

**Comment by xhuljo-inovalab** [comment]
We added a `transition: all 0.3s ease-in-out` to every  `.ssr-carousel-slide` element and it seems to bring this issue.  I am not entirely sure why that should be an issue.

**Comment by weotch** [comment]
The component does some measuring of the size of elements in the DOM ... maybe that messed up with calculations it's making.  Anyhow, glad it's working
