### ISSUE TITLE
Current structure does not allow for buttons to be positioned outside of carousel

### ISSUE THREAD

**Issue by sjstark** [BKWLD/vue-ssr-carousel#29]
Current structure nests the arrows within the track/mask. If they were pulled to outside of this (similar to dots) it would allow for the next and back buttons to be positioned as required per design.

**Comment by weotch** [comment]
Can I see an example design?  I think the reason I put them inside the mask is that they could be vertically centered relative to it.

**Comment by sjstark** [comment]
The example I'm working on doesn't have a design created by our design team, but really I feel like any form of text-based carousel wouldn't want the arrows hovering over top of the component. My simple work around for the time being is just make sure the content has padding within each slide.

<img width="1188" alt="Screen Shot 2022-01-26 at 7 59 21 PM" src="https://user-images.githubusercontent.com/6759557/151272482-385a990b-4a5a-46b2-a49d-c9f2f91d45a1.png">

Ugly example with too much text and my simple solution:
<img width="592" alt="Screen Shot 2022-01-26 at 8 03 16 PM" src="https://user-images.githubusercontent.com/6759557/151272534-0a3d62f0-a39a-4db6-a85e-cd1c44507ffa.png">

w/o padding:
<img width="600" alt="Screen Shot 2022-01-26 at 8 04 08 PM" src="https://user-images.githubusercontent.com/6759557/151272603-46ef837f-5256-4ca1-b52f-5713eb179401.png">

**Comment by weotch** [comment]
I think padding is a great solve ... not really sure how moving out of `mask` would help here anyhow.  What did you have in mind, UI wise, if it was moved out of the mask element?
