### ISSUE TITLE
While swiping through panes on desktop, if you drag outside of the carousel or window dots and arrows won't update

### ISSUE THREAD

**Issue by sjstark** [BKWLD/vue-ssr-carousel#31]
Description:

- When a user tries to drag outside the carousel to view the next or previous item, notice that the highlight in the carousel dots is not following the order of the items. If the user goes to the first item, the highlight will stay in the second carousel dot.
- NOTE: Carousel dot highlight will be correct if dragging gestures are made inside the carousel.

Expected behavior:

- Carousel dots highlight should be anchored to the current image item in the carousel.

Browser:

Windows 10 - Chrome, Edge, Firefox
macOS (10.15.7) - Chrome, Edge, Firefox

URL:

- https://prod-www.cor.bukwild.com/products/100-california-everyday

Steps:

1. Load the URL.
2. Go to the Carousel.
3. Try dragging the carousel.
4. Drag outside the carousel.
5. Observe that the next or previous image will appear.
6. Verify that the carousel dot icon highlights the incorrect product.

https://user-images.githubusercontent.com/77567/155433377-05dd9485-52d3-4f46-a949-a5c3762f4043.MP4

---

https://app.asana.com/0/0/1201831809994865/f

**Comment by weotch** [comment]
Wonder if this is related to the carousel drag getting "sticky" when right clicking inside of it...
