### ISSUE TITLE
Noticed Slides Jumping back on looping slide

### ISSUE THREAD

**Issue by sjstark** [BKWLD/vue-ssr-carousel#46]
https://vue-ssr-carousel.netlify.app/looping#looping-with-multiple-slides-per-page

If you advance one slide, `Slide 2` sits for half a second, then gets updated to `Slide 1`

https://user-images.githubusercontent.com/6759557/155593517-1771c1d4-2a03-422e-bfe1-cbf37b4b83ad.mov

**Comment by weotch** [comment]
Gotcha, thanks for the bug report!

**Comment by weotch** [comment]
This is an issue with nuxt/content and how it renders components that do weird things with slots.  I'm refactoring all the demo components to not depend on rendering slides in the markdown.
