### ISSUE TITLE
How to use on nuxt js?

### ISSUE THREAD

**Issue by irfnrdh** [BKWLD/vue-ssr-carousel#50]
after import gets some error, define but cannot be used. How to import component?

**Comment by irfnrdh** [comment]
😄 after 1 hour 

```
import` SsrCarousel from 'vue-ssr-carousel'
export default {
  name: "SimpleSlider",
  components: {
    'Slider': SsrCarousel,
  }
}
```
Sorry...

**Comment by weotch** [comment]
In 1.1.0 you can now do:

```
// nuxt.config.js
export default {
  buildModules: [ 'vue-ssr-carousel/nuxt' ]
}
```

**Comment by tiborpino** [comment]
Does it support nuxt 3?

**Comment by ErriourMe** [comment]
> In 1.1.0 you can now do:
> 
> ```
> // nuxt.config.js
> export default {
>   buildModules: [ 'vue-ssr-carousel/nuxt' ]
> }
> ```

But it doesnt work (Nuxt 2.15.8).
> Unknown custom element: <ssr-carousel> - did you register the component correctly?
