### ISSUE TITLE
Slides seem to never re-render when external props change

### ISSUE THREAD

**Issue by jonjahr** [BKWLD/vue-ssr-carousel#55]
I tried to use a `ssr-carousel` as a nav for a second `ssr-carousel`.  It mostly worked, but ssr-carousel seemed to never re-render the stale default slot when an outside prop changed (`carouselIndex`).  I tried simply adding a `.active` class to the active slide, but the element classes never changed when the active slide changed, making me think it's a re-rendering issue.  For now I worked around this using CSS selectors and data attributes.

To reproduce:
- Checkout COR branch `ssr-carousel-as-nav`
- Go to `http://localhost:3000/demo-tout-carousel`

![Kapture 2022-03-03 at 15 59 53](https://user-images.githubusercontent.com/6802815/156673737-1e2ae626-cded-4b33-9d5f-c4500ef7185b.gif)

**Comment by weotch** [comment]
I think this is related to #54...

**Comment by weotch** [comment]
Ok, this should be fixed now. I added a new demo at the end of the page on https://vue-ssr-carousel.netlify.app/misc to proof this out.  And your test page is working now as well:

https://user-images.githubusercontent.com/77567/156704519-9cd3d194-fe5c-4055-96e7-50a5258ab91b.mov

**Comment by jonjahr** [comment]
Nice!  I’ll check it out tomorrow.
________________________________
