### ISSUE TITLE
Windows 10 Edge cursor bug

### ISSUE THREAD

**Issue by jonjahr** [BKWLD/vue-ssr-carousel#60]
Throwing this foxhole ticket here:

Description:

Upon dragging the carousel over the image or copy, notice that the hand cursor will not change into a drag cursor. Only happens when dragging the current item.

Expected behavior:

Is this a limitation? If not, cursor icons should be consistent with drag gestures.

Browser:

Windows 10 - Chrome, Edge

**Comment by weotch** [comment]
Can you gimme the link to the Asana task?  Hoping there is a vid there cause I don't really get it yet.

**Comment by weotch** [comment]
See https://app.asana.com/0/0/1201922496048500/f

**Comment by weotch** [comment]
@jonjahr, closing this since https://app.asana.com/0/0/1201922496048500/f was resolved ... issue was maybe fixed by some other fix

**Comment by jonjahr** [comment]
Here’s the ticket: https://app.asana.com/0/1201922496048500/1201922496048500
________________________________
