### ISSUE TITLE
[BUG] `slot is not iterable` error

### ISSUE THREAD

**Issue by Razz21** [BKWLD/vue-ssr-carousel#63]
Hey,
This component is great, but I found it gives me an error when carousel slides are generated from async request - when default slot is empty during render
![image](https://user-images.githubusercontent.com/32792205/162279708-b7a42277-b756-4079-b42d-2a0b6c66f86e.png)

I believe carousel component should provide a fallback value for empty slot untill slides are available to prevent from ugly workarounds and `if's` statements.

regards,
Andrzej

**Comment by weotch** [comment]
Yeah, I'll probably hold rendering of the whole component until slots are present ... I don't think `$slots.default` is reactive so I may need to poll for changes ... or maybe use the `updated()` hook?  Just thinking out loud here ...

**Comment by Razz21** [comment]
@weotch thanks for quick reply. The main issue I have is unknown slides amount. I am able to conditionally create placeholders, but pagination is not working properly after initial load when data length is different than placeholders length. 
Programmatic `forceUpdate` also does not recalculate component data.

**Comment by weotch** [comment]
This should be fixed in 1.4.0 now, there is a new demo of this at the end of the https://vue-ssr-carousel.netlify.app/misc demos.
