### ISSUE TITLE
Invalid Array Length error when trying to use on Axios get request

### ISSUE THREAD

**Issue by p3lican** [BKWLD/vue-ssr-carousel#66]
Hello,

Great plugin but maybe I am doing something incorrectly.
I can get the slides to load when they are static/hard-coded in, but if I try to use data from an axios request, then use v-for, I get an "Invalid Array Length" error.

Is there documentation on how to use this slider with dynamic data?

Code:
```
<template>
  <ssr-carousel v-if="posts" :slides-per-page='3' show-dots show-arrows :peek-right='60' :peek-left='60' paginate-by-slide feather :gutter='20'>
    <div v-for="post in posts" class="slide">{{post.title}}</div>
  </ssr-carousel>
</template>
```

In the <Script>:

```
methods: {
  async fetchSomething() {
            this.loading = true;
            const postFetch = await this.$axios.$get(latestArticles, { headers:{'accessToken':this.$config.apiPrivate}})
            this.postFetch = postFetch;
            this.posts = this.postFetch.response.result
            this.loading = false
   },
}
created() {
    this.fetchSomething()
 },
```

Please let me know if you need more information.

![ssnuxt](https://user-images.githubusercontent.com/28329205/164288131-6499bac7-728e-4635-98a1-b2bc8f098ca6.JPG)

**Comment by p3lican** [comment]
I believe I was able to fix this with changing the v-if on the carousel main component to v-if="posts.length > 0"

Working:
```
      <ssr-carousel v-if="posts.length > 0" :slides-per-page='3' show-arrows  loop center :peek-left='60' :peek-right='60' :autoplay-delay='3' paginate-by-slide>
          <div v-for="(post,index) in posts" :key="index">{{post.title}}</div>
       </ssr-carousel>
```

**Comment by weotch** [comment]
Curious, did you initialize `posts` as an empty array in your component data first?  Like:

```
export default {
  data() {
    return {
      posts: []
    }
  }
}
```

Since #64 I wouldn't expect an error if there were no slides initially.  Though I like your `v-if` solution, that's what I'd do in my own usage.

**Comment by p3lican** [comment]
Yeah that's what I have. Seemed odd but my dev environment wouldn't load the page so I couldn't inspect it.
Searching the error message is what brought me to the solution of discreetly checking the array length rather than just the existence of "posts".

All good now, working beautifully. Thanks!
