### ISSUE TITLE
Without inline styling

### ISSUE THREAD

**Issue by frontero** [BKWLD/vue-ssr-carousel#68]
Is it possible to use it without inline styling? Inline styling is blocked by security reasons on our website.

**Comment by weotch** [comment]
Not at the moment.  This package dynamically creates media queries based on the props that are passed in.  To make that work without inline styling we'd need some way to extract those to a CSS file.  I'm not really sure how that could be accomplished...

Can you tell me more about your site?  Like is there actually some software running on your site the blocks inline styling?  I'm wondering if this is something we should expect to encounter on other sites.

**Comment by frontero** [comment]
Yes, the company has blocked for security reasons. On this website you can read for what reason: https://stackoverflow.com/questions/30653698/csp-style-src-unsafe-inline-is-it-worth-it/31759553

**Comment by weotch** [comment]
I see, thanks for the link!  

I'm gonna close this for now because I don't think we'll be implementing a workaround anytime soon for this.
