### ISSUE TITLE
Slides with different width

### ISSUE THREAD

**Issue by Scarwolf** [BKWLD/vue-ssr-carousel#70]
Hey,

This is really a great component. I would suggest a boolean prop that allows switching between a fixed width and a dynamic width,

Currently, the component is using the fixed-width by default, which means that every slide is full width depending on the peek settings. 
I think it would be a great addition to allow for a dynamic width, so if you show a few images in the slider that have a different width, they wouldn't create blank space. Of course, `slides-per-page` wouldn't work if you set this prop.

What do you think?

**Comment by weotch** [comment]
Yeah, I could see adding that in the future 👍
