### ISSUE TITLE
Switch peek values after swipe

### ISSUE THREAD

**Issue by sdeseive** [BKWLD/vue-ssr-carousel#77]
Hi,

i want to change the `peek-left` and the `peek-right` value after swiping to the next image, but after changing the peek values the calculation of the `transform: translateX()` value is wrong. Is there a way to change the peek values on the fly?

I start with `peek-left: 0` and `peek-right: 15%`, after the first change I want both to be `15%`, so that the 2nd image is centred. when we reach the last image, peek-left should be  `15%` and `peek-right 0`

best regard

**Comment by weotch** [comment]
If you ran [`capturePeekingMeasurements()`](https://github.com/BKWLD/vue-ssr-carousel/blob/2b14eda8c15f6a43b4023b311dc9fc0c96237bf0/src/concerns/peeking.coffee#L71) after changing those values, I think it should force the `translateX()` to update.  Like if you did `$refs.slider.capturePeekingMeasurements()` from your code.

I may add a watcher to the `peekLeft` and `peekRight` props to calls this automatically if those values change...
