### ISSUE TITLE
Slider doesn't work with Nuxt 2

### ISSUE THREAD

**Issue by ErriourMe** [BKWLD/vue-ssr-carousel#80]
I have a problem with this slider in Nuxt 2.15.8.
I added module in buildModules, then called `<ssr-carousel>` component:

```
<ssr-carousel ref="reviewsSlider" class="virtual-slider">
  <div
    v-for="(item, i) in data"
    :key="`review-item-${i}`"
    class="slide"
  >
    <ReviewItem
        class="reviews-block__item-card"
        :data="item"
        :index="i"
        has-image
        @selectedItem="showFull"
      />
  </div>
</ssr-carousel>
```

After that I'm receiving error (as if the module is not loaded)
> Unknown custom element: \<ssr-carousel\> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

Why?

**Comment by ErriourMe** [comment]
All works if load component directly:

```
components: {
    ...
    SsrCarousel: () => import('vue-ssr-carousel'),
  },
```

**Comment by weotch** [comment]
Huh, it's working fine for me with the `buildModules` load style 🤷
