### ISSUE TITLE
"Duplicate keys detected" warn using infinitie carousel

### ISSUE THREAD

**Issue by ErriourMe** [BKWLD/vue-ssr-carousel#81]
A lot of "Duplicate keys detected" warns is appearing when v-for and "loop: true" used. 

```
[Vue warn]: Duplicate keys detected: 'review-item-26bs8qirlj55'. This may cause an update error.

found in

---> <ReviewsBlock>
       <Page> at components/Page.vue
         <Index> at pages/index.vue
           <Nuxt>
             <Default> at layouts/default.vue
               <Root>
```

Code:
```
<SsrCarousel :loop="true">
    <div
        v-for="(item, i) in data"
        :key="`review-item-${generate(i)}`"
        class="slide"
    >
        <ReviewItem
            class="reviews-block__item-card"
            :data="item"
            :index="i"
        />
    </div>
</SsrCarousel>
```

It should be fixed for mirrors of slide (add some suffixes for copied slides?)

**Comment by ErriourMe** [comment]
Removing `:key` props doesn't resolve the problem
> vue.runtime.esm.js:620 [Vue warn]: Duplicate keys detected: '__vlist_2_29__'. This may cause an update error.

**Comment by weotch** [comment]
You're sure that `generate(i)` is returning unique values for each `.slide`?

**Comment by ErriourMe** [comment]
> You're sure that `generate(i)` is returning unique values for each `.slide`?

Yes, it just was attempt to unferstand, will be it work with random key or not. 
```
generate(payload) {
    return String(payload) + Math.random().toString(36).slice(2)
},
```

It looks like the carousel clones slides after they have been assigned key strings.

**Comment by weotch** [comment]
Yeah, adding some prefix to the clones sounds good.  Surprised I haven't run into this issue in my usage!
