### ISSUE TITLE
Need to force rerender to dinamically add slides.

### ISSUE THREAD

**Issue by mikimoresi** [BKWLD/vue-ssr-carousel#93]
Dear Sirs,
very nice component again.

As already stated in other closed issues pushing or unshifting new items inside the slides array is not causing the component to properly re-render, I see the added component but they have "display: none", navigations arrow stays disabled and it is not possible to proceed sliding to the just added elements.
If I use a work around making the component re-rendere by a temporary v-if, it starts consider new items properly.

Thank you

**Comment by weotch** [comment]
Check out the "Carousel doesn't render until there are slides" demo on https://vue-ssr-carousel.netlify.app/misc.  I'm not seeing any errors there.  Can you provide a demo of the issue you're seeing?

**Comment by mikimoresi** [comment]
My fault,
on the demo code sample under "misc -> Add slide" there is not the `:key` prop on `<ssr-carousel>`
I figured out where the `:key` should be placed debugging the demo.

**Comment by weotch** [comment]
My bad too,  looks like I don't show that in the docs page.
