### ISSUE TITLE
Issue with disabling behavior when a peek and loop are specified

### ISSUE THREAD

**Issue by fgrasu** [BKWLD/vue-ssr-carousel#95]
Hi there. I noticed that setting `slidesPerPage` in `responsive` a value that is equal or higher than the carousel length, while the `loop` is `true`, will break the carousel. In this case, I think `slidesPerPage` value should at least default to the carousel length value - 1. What do you guys think?

This is how is displayed: 
![image](https://user-images.githubusercontent.com/101188606/191059239-14279f2e-776e-4ab5-b92d-a59299678a35.png)

**Comment by weotch** [comment]
I can't reproduce this issue.  In [this CodeSandbox link](https://codesandbox.io/p/github/BKWLD/vue-ssr-carousel/issue-95?file=%2Fdemo%2Fcomponents%2Fdemos%2Fmisc%2Fdisabling.vue&selection=%5B%7B%22endColumn%22%3A7%2C%22endLineNumber%22%3A6%2C%22startColumn%22%3A7%2C%22startLineNumber%22%3A6%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl89dr3mh0025lnev0c9wg6u4%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fdemo%252Fcomponents%252Fdemos%252Fmisc%252Fdisabling.vue%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cl89ds8cg00e63b6h6w2pi9nr%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252Fmisc%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cl89ds4p000c53b6hnw8q1wqw%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D) I've changed the first demo on that page to `loop` and I have more `slidesPerPage` than the actual number of slides.  

![image](https://user-images.githubusercontent.com/77567/191135535-e5866d99-be26-48ff-8a78-c1aa4c3c5aaa.png)

The slides are rendering as expected for me.

Regarding

> I think slidesPerPage value should at least default to the carousel length value - 1

In this case, I think you'd maybe do something like:

```vue
<ssr-carousel :slides-per-page='Math.min(3, slides.length - 1) />
```

Or something similar.

**Comment by fgrasu** [comment]
@weotch I played with the settings a little more. It seems like the `peek` prop is actually the issue when is set on default settings. See if you can reproduce it now. Not a big issue though, I can use your solution with `Math.min`, thanks.
![image](https://user-images.githubusercontent.com/101188606/191200561-f52f8c0f-43c2-4d65-8feb-aa4bc0886598.png)

**Comment by weotch** [comment]
Oh yeah, [I see what you mean](https://codesandbox.io/p/github/BKWLD/vue-ssr-carousel/issue-95?file=%2Fdemo%2Fcomponents%2Fdemos%2Fmisc%2Fdisabling.vue&selection=%5B%7B%22endColumn%22%3A16%2C%22endLineNumber%22%3A8%2C%22startColumn%22%3A16%2C%22startLineNumber%22%3A8%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl89dr3mh0025lnev0c9wg6u4%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fdemo%252Fcomponents%252Fdemos%252Fmisc%252Fdisabling.vue%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cl89ds8cg00e63b6h6w2pi9nr%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252Fmisc%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cl89ds4p000c53b6hnw8q1wqw%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)

![image](https://user-images.githubusercontent.com/77567/191284590-7c48309e-1673-498a-8b04-2a628c7f397a.png)

I'm going to keep this open to fix
